<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<pre>
    Here's a comparison of common string functions in both JavaScript and Python, along with sample code for each.

| Operation               | JavaScript                                | Python                                      | Example in JavaScript                                                                                                                                     | Example in Python                                                                                                       |
|-----------------------------|-----------------------------------------------|------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------|
| Create a string          | let str = "Hello";                         | str = "Hello"                               | let str = "Hello";                                                                                                                                          | str = "Hello"                                                                                                            |
| Length of string         | str.length                                 | len(str)                                    | let str = "Hello"; console.log(str.length); // 5                                                                                                             | str = "Hello"; print(len(str)) # 5                                                                                       |
| Access by index          | str[1]                                     | str[1]                                      | let str = "Hello"; console.log(str[1]); // e                                                                                                                 | str = "Hello"; print(str[1]) # e                                                                                        |
| Concatenate strings      | str1 + str2                                | str1 + str2                                 | let str1 = "Hello", str2 = " World"; let result = str1 + str2; console.log(result); // Hello World                                                            | str1 = "Hello"; str2 = " World"; result = str1 + str2; print(result) # Hello World                                       |
| Uppercase                | str.toUpperCase();                         | str.upper()                                | let str = "hello"; let upper = str.toUpperCase(); console.log(upper); // HELLO                                                                                | str = "hello"; upper = str.upper(); print(upper) # HELLO                                                                 |
| Lowercase                | str.toLowerCase();                         | str.lower()                                | let str = "HELLO"; let lower = str.toLowerCase(); console.log(lower); // hello                                                                                | str = "HELLO"; lower = str.lower(); print(lower) # hello                                                                 |
| Trim spaces              | str.trim();                                | str.strip()                                | let str = "  hello  "; let trimmed = str.trim(); console.log(trimmed); // "hello"                                                                             | str = "  hello  "; trimmed = str.strip(); print(trimmed) # hello                                                         |
| Substring                | str.substring(1, 4);                       | str[1:4]                                   | let str = "hello"; let sub = str.substring(1, 4); console.log(sub); // ell                                                                                    | str = "hello"; sub = str[1:4]; print(sub) # ell                                                                          |
| Replace substring        | str.replace("ell", "ipp");                 | str.replace("ell", "ipp")                  | let str = "hello"; let replaced = str.replace("ell", "ipp"); console.log(replaced); // hippo                                                                  | str = "hello"; replaced = str.replace("ell", "ipp"); print(replaced) # hippo                                             |
| Split string             | str.split(" ");                            | str.split(" ")                             | let str = "hello world"; let words = str.split(" "); console.log(words); // ["hello", "world"]                                                                | str = "hello world"; words = str.split(" "); print(words) # ['hello', 'world']                                           |
| Join strings             | arr.join(" ");                             | " ".join(arr)                              | let arr = ["hello", "world"]; let joined = arr.join(" "); console.log(joined); // hello world                                                                 | arr = ["hello", "world"]; joined = " ".join(arr); print(joined) # hello world                                            |
| Find substring           | str.indexOf("ell");                        | str.find("ell")                            | let str = "hello"; let index = str.indexOf("ell"); console.log(index); // 1                                                                                   | str = "hello"; index = str.find("ell"); print(index) # 1                                                                 |
| String starts with       | str.startsWith("He");                      | str.startswith("He")                       | let str = "Hello"; console.log(str.startsWith("He")); // true                                                                                                 | str = "Hello"; print(str.startswith("He")) # True                                                                        |
| String ends with         | str.endsWith("lo");                        | str.endswith("lo")                         | let str = "Hello"; console.log(str.endsWith("lo")); // true                                                                                                   | str = "Hello"; print(str.endswith("lo")) # True                                                                          |
| Repeat string            | str.repeat(3);                             | str * 3                                    | let str = "abc"; console.log(str.repeat(3)); // abcabcabc                                                                                                      | str = "abc"; print(str * 3) # abcabcabc                                                                                  |
| Reverse string           | str.split("").reverse().join("");          | str[::-1]                                  | let str = "hello"; let reversed = str.split("").reverse().join(""); console.log(reversed); // olleh                                                           | str = "hello"; print(str[::-1]) # olleh                                                                                  |
| Check if numeric         | !isNaN(str);                               | str.isdigit()                              | let str = "12345"; console.log(!isNaN(str)); // true                                                                                                           | str = "12345"; print(str.isdigit()) # True                                                                               |
| Count occurrences        | str.split("l").length - 1;                 | str.count("l")                             | let str = "hello"; let count = str.split("l").length - 1; console.log(count); // 2                                                                             | str = "hello"; count = str.count("l"); print(count) # 2                                                                  |
| Check if substring exists| str.includes("ell");                       | "ell" in str                              | let str = "hello"; console.log(str.includes("ell")); // true                                                                                                   | str = "hello"; print("ell" in str) # True                                                                                |
| Remove specific characters| str.replace(/[a]/g, "");                  | str.replace("a", "")                       | let str = "banana"; let removed = str.replace(/[a]/g, ""); console.log(removed); // bnn                                                                        | str = "banana"; removed = str.replace("a", ""); print(removed) # bnn                                                     |
| Format string            | ``Hello ${name}``                            | "Hello {}".format(name)                    | let name = "Jon"; console.log(Hello ${name}); // Hello Jon                                                                                                   | name = "Jon"; print("Hello {}".format(name)) # Hello Jon                                                                 |

 Key Differences:
- String Mutability: In both JavaScript and Python, strings are immutable. This means methods like replace() return a new string rather than modifying the original string.
- Formatting: JavaScript uses template literals (`` ${variable} ``) for string interpolation, while Python uses .format() or f-strings (f"Hello {variable}").
- String manipulation: Python uses more concise slicing, while JavaScript often requires the use of .split(), .reverse(), and .join() to achieve similar results.

Let me know if you'd like more examples or detailed explanations for any of the functions!
</pre>
</body>
</html>