<?php
require "wedding.php";
class Wedding2 extends Wedding {

    public function eat()
    {
        parent::eat(); // TODO: Change the autogenerated stub
        //echo "We are eating Korean food <hr>";
    }

}
$wedding2 = new Wedding2();

echo $wedding2->budget."<hr>";
